name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    name: Backend & Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e backend[dev] -e ai_agent[dev] -e content_safety[dev] pytest-cov
      - name: Lint & format check
        run: |
          black --check backend ai_agent content_safety
          ruff check backend ai_agent content_safety
      - name: Backend tests with coverage
        working-directory: backend
        run: pytest --cov=app --cov-report=term-missing --cov-fail-under=80
      - name: AI agent tests
        working-directory: ai_agent
        run: pytest
      - name: Content safety tests
        working-directory: content_safety
        run: pytest

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Lint
        working-directory: frontend
        run: npm run lint
      - name: Prettier check
        working-directory: frontend
        run: npm run format:check
      - name: Build
        working-directory: frontend
        run: npm run build

  realtime:
    name: Realtime Gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: realtime/package-lock.json
      - name: Install dependencies
        working-directory: realtime
        run: npm ci
      - name: Lint
        working-directory: realtime
        run: npm run lint
      - name: Prettier check
        working-directory: realtime
        run: npm run format:check
      - name: Build
        working-directory: realtime
        run: npm run build
